version: '3.1'

services:
  db:
    image: mysql:8.0.32
    restart: always
    container_name: exacta
    environment:
      MYSQL_DATABASE: 'exactabank'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'